output_dir: ~/experiments/

dataset:
  class: WN18RRInductive
  path: ~/datasets/knowledge_graphs/
  version: {{ version }}

task:
  class: InductiveKnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: no
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32

train:
  num_epoch: 20

metric: mrr